services:
  deepresearch:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    volumes:
      # Optional: Mount a volume for logs
      - ./logs:/app/logs
    networks:
      - deepresearch-network

  # Optional: Add a reverse proxy (nginx) if needed
  # nginx:
  #   image: nginx:alpine
  #   ports:
  #     - "80:80"
  #   volumes:
  #     - ./nginx.conf:/etc/nginx/nginx.conf
  #   depends_on:
  #     - deepresearch
  #   networks:
  #     - deepresearch-network

networks:
  deepresearch-network:
    driver: bridge

volumes:
  logs:
